name: laundry
description: A new Flutter project.

version: 1.0.13+17

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc_pattern: ^2.4.1+1
  shared_preferences: 0.5.3+5
  font_awesome_flutter: ^8.5.0
  blue_thermal_printer: ^1.0.9
  responsive_screen: ^1.0.0
  flutter_spinkit: ^4.0.0
  cryptoutils: ^0.4.0
  cached_network_image: ^1.1.2+1
  indonesia: ^1.0.1
  rxdart: ^0.22.4
  flutter_alert: ^0.4.0
  http: ^0.12.0+2
  package_info: ^0.4.0+10
  flutter_slidable: ^0.5.4
  lazy_load_scrollview: ^1.0.1
  date_format: ^1.0.8
  loader_search_bar: ^1.0.3+3
  bn_refresh_indicator: ^1.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_app_host: ^0.2.2

flutter:
  uses-material-design: true
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg